# vim: nospell
#
language: c
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.stack/snapshots
    - .stack-work/install

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.18
      - cabal-install-1.22
      - cabal-install-1.24
      - cabal-install-2.0
      - alex
      - c2hs
      - happy

compiler:
  - GHC-8.6.1
  - GHC-8.4.1
  - GHC-8.2.1
  - GHC-8.0.2
  - GHC-7.10.3
  - GHC-7.8.4

env:
  # global:
  matrix:
    - CUDA=8.0.61-1
    - CUDA=7.5-18
    - CUDA=7.0-28
    - CUDA=6.5-14

matrix:
  fast_finish: true
  # allow_failures:

before_install:
  - export GHC=${CC:4}
  - unset CC
  - |
      case ${GHC%.*} in
        7.8)  export CABAL=1.18 ;;
        7.10) export CABAL=1.22 ;;
        8.0)  export CABAL=1.24 ;;
        8.2)  export CABAL=2.0  ;;
        8.4)  export CABAL=2.0  ;;
        8.6)  export CABAL=2.0  ;;
      esac
  - export PATH=/opt/cabal/$CABAL/bin:$HOME/.cabal/bin:$PATH
  - export CUDA_INSTALL_EXTRA_LIBS=0
  - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh
  - source .travis/update-ghc-settings.sh

  # build environment
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - nvcc --version

install:
  - travis_retry stack build --fast --only-dependencies --no-terminal

script:
  - travis_retry stack build --fast --no-terminal --haddock --no-haddock-deps

after_success:
  - source .travis/update-accelerate-buildbot.sh

after_failure:
  - dmesg
  - ls -R /usr/local/cuda*

